### ISSUE TITLE
Does not compile on OSX with Node.js 6

### ISSUE THREAD

**Issue by rwaldron** [tessel/node-usb#121]
This was discovered while updating t2-cli's travis.yml: https://travis-ci.org/tessel/t2-cli/jobs/125957491

```
g++-4.8: error: unrecognized command line option '-stdlib=libc++'
```

**Comment by tcr** [comment]
Not sure why this is being built with g++, but we don't support g++ for compilation on OS X.

**Comment by tcr** [comment]
If you wanted to, though, remove `-stdlib=libc++` from the binding.gyp file. If you can make this change conditional on clang/gcc, I'll be happy to merge it in.

**Comment by tcr** [comment]
http://stackoverflow.com/a/19774902/6728025
