### ISSUE TITLE
Question: Transfer Format

### ISSUE THREAD

**Issue by 360disrupt** [tessel/node-usb#123]
Is there any specific format for outgoing messages? E.g. Buffer of binary

```
dec2bin = (decimalArray)->
  binArray = []
  for decimal in decimalArray
    binArray.push(decimal >>> 0)
  return binArray

exports.sendToUsbDevice = (iface, msg, callback) ->
  outEndpoint = iface.endpoints[1]
  checksum = calculateChecksum msg
  intMsg = [80,0,1,parseInt(msg),checksum]
  bufferMsg = new Buffer(dec2bin(intMsg))
  outEndpoint.transfer bufferMsg, (err)->
```

From the tests it seems like a plain array of integers is sent
`outEndpoint.transfer [1,2,3,4], (e) ->`
But it also isn't a real world example.

**Comment by kevinmehall** [comment]
They're arrays or Buffers of bytes. The contents depend solely on the device.
