### ISSUE TITLE
Issue installing on raspberry PI 3

### ISSUE THREAD

**Issue by rob-cowsley** [tessel/node-usb#139]
Having some trouble installing using npm on the Raspberry PI 3 as per the attached screenshot and log. 

Error: `make` failed with exit code: 2

![npm-usb](https://cloud.githubusercontent.com/assets/5008646/18575260/ad3d389a-7c29-11e6-9d35-0c5c34617fbd.jpg)

[npm-debug.txt](https://github.com/tessel/node-usb/files/476049/npm-debug.txt)

**Comment by julien-digilink** [comment]
Same issue for me on m'y Rasperry Pi 3

**Comment by rob-cowsley** [comment]
I ended up switching to a different distro to get this working.

**Comment by julien-digilink** [comment]
@rob-cowsley which one please ? I still experiment the same problem. Thanks

**Comment by rob-cowsley** [comment]
I used he pre-built kali image as a base from here:

http://docs.kali.org/kali-on-arm/install-kali-linux-arm-raspberry-pi

**Comment by georgkreimer** [comment]
Really? How can this be the solution?

**Comment by pr1ntr** [comment]
seriously?

**Comment by rwaldron** [comment]
@pr1ntr @georgkreimer Looks like this was a permissions problem—how would you suggest that ths project fix permissions on a device or machine that it has no access to?

**Comment by pr1ntr** [comment]
ok so apparently this was an issue with 1.2. 1.3.1 it works fine. I was trying to use it with 
`node-fadecandy` and their npm package used 1.2. So I was able to install just fine on a raspberry pi without sudo. Sorry for the snide remark.

**Comment by rwaldron** [comment]
I'm glad everything is working now ❤️
