### ISSUE TITLE
Error in Electron

### ISSUE THREAD

**Issue by woodev01** [tessel/node-usb#140]
I'm running Windows 7 in 64 bit and ran into a weird error during compilation of my Electron App. As it was attempting to launch I got this error (all the app is doing with node-usb is requiring it).

A Javascript error occurred in the main process:

Uncaught Exception:
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\?\C:\Users{{path}}\usb_bindings.node
  at Error (native) ...

I have no idea what this means. The only similar issue I could find was this issue 

> > https://github.com/brave/browser-laptop/issues/350

They suggested that it could be an architecture interference issue, because I'm using 64-bit. Any ideas how to move on with this??

**Comment by rwaldron** [comment]
Did you rebuild node-usb for Electron?

**Comment by woodev01** [comment]
I hadn't at the time of posting this issue. I now have and I am still getting this same error.

**Comment by rwaldron** [comment]
Ok, thanks for the follow up. Can you create a test case for this? If you put it into a repo, then I can clone it and work on reproduction locally (on windows machine). Without that, I'd have to try to guess to piece it together

**Comment by woodev01** [comment]
Literally all I have done is make an index.html, main.js. The main.js has your boilerplate createWindow(). It has var usb = require('usb'). I have npm installed electron, electron-rebuild, and node-usb. They are all installed. I reinstalled all of them. I used electron rebuild without an issue, then I tried to run the program and an alert popped with that output. Is node-usb native 32bit?

**Comment by rwaldron** [comment]
Ok, that might be enough to get me started. I'll ping back if I have any further questions :)

**Comment by rwaldron** [comment]
Using Windows 10 (64-bit), here's what I've done: 

1. `git clone https://github.com/electron/electron-quick-start`
2. `cd electron-quick-start`
3. `npm install`
4. `npm install usb` //  completes successfully
5. `npm install --save-dev electron-rebuild`
  - This won't install for me. Looks like it's failing on nslog :\

**Comment by woodev01** [comment]
Yeah, that install takes some work. You need the C++ file from Visual Studio 13 and you need Python 2.7

**Comment by rwaldron** [comment]
Ok, I'll take another run at it.

**Comment by BlackWolf** [comment]
I'm trying to do the same thing and I am running into 

`Uncaught Error: Cannot find module 'C:\path\to\my\project\node_modules\usb\src\binding\usb_bindings.node`

which I assume is a similar issue. I do have python2.7, but what does "the C++ file from Visual Studio 13" refer to?

thanks!

**Comment by digitalentity** [comment]
I have the same issue. Win7 x64, app crashes at `var usb = require('usb');` with the same message. @rwaldron any suggestion where to dig?

**Comment by Croxy** [comment]
Has anyone been able to resolve this?

I am getting the same error related to the USB package as above. 

![image](https://cloud.githubusercontent.com/assets/5749114/22803986/c55312c6-eedc-11e6-870c-6ade0eabdc6a.png)

**Comment by eohan** [comment]
Hi, Has anyone been able to resolve this ?

**Comment by rwaldron** [comment]
Electron's docs describe additional steps needed when using compiled modules: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by acr14** [comment]
I'm running into the same issue and was wondering if anyone has found a solution?

**Comment by eohan** [comment]
@acr14 , https://github.com/tessel/node-usb/issues/140#issuecomment-291583363 worked for me.

**Comment by chenamy2017** [comment]
I used electron-rebuild resolve this .

**Comment by vikjsdev** [comment]
Does anybody found solution?
