### ISSUE TITLE
unable to `findByIds`

### ISSUE THREAD

**Issue by wkentdag** [tessel/node-usb#145]
I'm attempting to detect when a specific USB device gets mounted on a Windows machine. So far I haven't been able to get a result back from `findByIds` even with the device already plugged in. For demo purposes I'm using my iPhone.

* First I found my phone's VID and PID with instructions from [an article](https://support.shippingeasy.com/hc/en-us/articles/203086919-How-to-Find-the-Vendor-ID-VID-and-Product-ID-PID-for-my-USB-scale-Applet-Integration-) using Windows Device Manager. (ps - I would suggest adding an example of VID and PID syntax to the readme, and maybe linking to an article such as this for how to go about finding those IDs for a specific device. happy to PR it! 😄)

* The hardware ID string in Device Manager is `USB\VID_05AC&PID_12A8&REV_0702`, and, per the article's suggestions and [example syntax from this package's test file](https://github.com/tessel/node-usb/blob/master/test/usb.coffee#L43), I wound up with something like this: `usb.findByIds(0x05AC, 0x0702)`

```js
// more context
findDevice () {
  return new Promise((resolve, reject) => {
    let partition = usb.findByIds(0x05AC, 0x0702)
    if (partition) {
        resolve(partition)
    } else {
      reject(new Error('not found'))
    }
  })
}
```

I've been unable to get anything other than an error. I'm running Windows 10 via bootcamp on a macbook pro, node `v6.6.0`, and npm `v3.10.3`.

**Comment by kevinmehall** [comment]
In that hardware ID string, the PID is 0x12A8. The 0x0702 is the device revision. That syntax is a Windows thing. Everywhere else, VID and PID are just 16-bit integers.

Check out https://github.com/tcr/node-lsusb to list USB devices.
