### ISSUE TITLE
Help me out :-(

### ISSUE THREAD

**Issue by Shlok-Rajamanickam** [tessel/node-usb#146]
How to use this usb to read data from usb devices.
can i have example code.
im stuck here pls help me

**Comment by kevinmehall** [comment]
How to use this library depends entirely on what type of device you're trying to access. Here are a few resources I recommend for learning about USB:
http://www.beyondlogic.org/usbnutshell/usb1.shtml
USB Complete by Jan Axelson: http://janaxelson.com/usbc.htm

**Comment by Shlok-Rajamanickam** [comment]
Thanks kevin 👍 
for your information i'm using usb hid device which is exactly a card swiper.
