### ISSUE TITLE
Module version mismatch. Expected 50, got 48.

### ISSUE THREAD

**Issue by souravatwork** [tessel/node-usb#149]
Hi, 
I am trying to use node-usb with Electonjs. But I faced error as follows when I require 'usb' : 
>ELECTRON_ASAR.js:178 Uncaught Error: Module version mismatch. Expected 50, got 48.

I am using:  
node version : 6.3.1
npm version: 3.10.3
electron version : 1.4.1
usb version : 1.2.0

Let me know which version need to use to solve this issue.
Thanks.

**Comment by hhff** [comment]
+1 I'm in the same boat!

**Comment by hhff** [comment]
@souravatwork - try running https://github.com/electron/electron-rebuild after you install node-usb.

Worked like charm for me!

**Comment by souravatwork** [comment]
@hhff  Thanks for your help :) . It is working now.

**Comment by prashanth-nani** [comment]
@souravatwork Thanks.. It's working now
