### ISSUE TITLE
Feature request: descriptors as ascii strings

### ISSUE THREAD

**Issue by Starefossen** [tessel/node-usb#15]
Any possibility to get the string descriptors in ascii text like `lsusb -v` does:

```
...
  iManufacturer           1 FTDI
  iProduct                2 FT232R USB UART
  iSerial                 3 A2001nh5
  bNumConfigurations      1
...
```

From what I can understand from [this thread](http://libusb.6.n5.nabble.com/Trying-to-get-serial-number-and-guessing-tty-mapping-td4341021.html) lsusb is using [libusb_get_string_descriptor_ascii](http://libusb.sourceforge.net/api-1.0/group__desc.html#gaf3f92d0a7465d49a5e61eb3f8689fae4)

**Comment by peteruithoven** [comment]
Could someone share an example? Easily with `controlTransfer` is a bit of a understatement as it requires 5 arguments, which are not exactly intuitively named.

**Comment by peteruithoven** [comment]
( I see you did add this convenience function `getStringDescriptor` in: https://github.com/tessel/node-usb/commit/7f6939fd42c19e91a4e4864202942e74d3568038 )
