### ISSUE TITLE
fail to install npm on node js 6

### ISSUE THREAD

**Issue by kenken64** [tessel/node-usb#160]
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: usb@^1.2.2
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.2.0, 1.1.2, 1.1.1, 1.1.0, 1.0.6, 1.0.5, 1.0.4, 1.0.3, 1.0.2,
 1.0.1, 0.3.11, 0.3.10, 0.3.9, 0.3.8, 0.3.8-beta1, 0.3.7, 0.3.5, 0.3.4, 0.3.2, 0
.3.2-1, 0.3.1, 0.3.0, 0.2.3, 0.2.2, 0.2.1, 0.2.0, 0.1.2, 0.1.1, 0.1.0
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! Please include the following file with any support request:

**Comment by kevinmehall** [comment]
You have a package depending on `usb@^1.2.2`, while the latest release is 1.2.0.
