### ISSUE TITLE
Can not install package on Linux64

### ISSUE THREAD

**Issue by hanhdt** [tessel/node-usb#171]
Hi,

I'm trying install node-usb from my project but seem like it don't have releases for Linux right?

![screenshot from 2017-02-23 15-40-52](https://cloud.githubusercontent.com/assets/3414312/23247618/8068a6b4-f9de-11e6-9033-23f744dac610.png)

Thanks.

**Comment by kevinmehall** [comment]
There are pre-built binaries for Windows and macOS, but it will build from source on Linux.

From the README:
>On Linux, you'll need libudev to build libusb. On Ubuntu/Debian: sudo apt-get install build-essential libudev-dev

Post the full error message if it fails to build.

**Comment by hanhdt** [comment]
I already fixed it after install node-gyp package.

Thanks you.
