### ISSUE TITLE
LIBUSB_ERROR_BUSY Raspberry Pi 3

### ISSUE THREAD

**Issue by victorlm125** [tessel/node-usb#174]
Firstable I had LIBUSB_ERROR_ACCESS that I fix adding permissions to usblib but now I have this error and I can't found out whats the reason because nobody uses this usb driver before my node server so I don't unsderstand.

Regards

**Comment by julienvincent** [comment]
I would also like a solution to this. I am getting this on the PiB 1

**Comment by julienvincent** [comment]
I did some research into this: The reason is that the pi attaches a kernel driver to connected devices. You need to check for a kernel driver and detach it before claiming the interface.

pseudo code:
```javascript
device.open()
const deviceInterface = device.interfaces[0]

let driverAttached = false
if (printerInterface.isKernelDriverActive()) {
   driverAttached = true
   deviceInterface.detachKernelDriver()
}

deviceInterface.claim()

// ... use the device

deviceInterface.release(() => {
   if (driverAttached) {
      deviceInterface.attachKernelDriver()
   }

   device.close()
})
```

**Comment by kevinmehall** [comment]
:+1: We should add a "Troubleshooting FAQ" section to the README with hints like this.

**Comment by kevinmehall** [comment]
Closing in favor of #182
