### ISSUE TITLE
node-pre-gyp ERR!

### ISSUE THREAD

**Issue by xueqino1** [tessel/node-usb#178]
when running "npm install usb" I got error :
node-pre-gyp ERR! Tried to download: https://github.com/tessel/node-usb/releases/download/1.2.0/usb_bindings-v1.2.0-node-v48-linux-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for usb@1.2.0 and node@6.10.0 (node-v48 ABI) (falling back to source compile with node-gyp) 

I access the url,The response is 404,how to fix it?
env: ubuntu16.04, node version v6.10.0,npm version 3.10.10 
thanks.

**Comment by kevinmehall** [comment]
There are no binary releases for Linux. You have to have the dependencies (see README) and it will compile from source.
