### ISSUE TITLE
How do i get the port name of a specific device?

### ISSUE THREAD

**Issue by Jeanmass** [tessel/node-usb#186]
Hey guys ! 

Thanks for this library, it's working great for me, except for one thing. I couldnt find a way to get the port name of a specific device (COMX, /dev/ttyUSB0)?  

I need the port name to open a port with serialport and send stuff to my arduino device, without the user having to select it manually.

Can it be done? Thanks !

**Comment by liyatang** [comment]
try [usb-detection](https://github.com/MadLittleMods/node-usb-detection)

**Comment by kevinmehall** [comment]
Correct, this library is for accessing USB devices that don't have in-kernel drivers, not usb-serial, so isn't a good fit for this use case.

**Comment by thegecko** [comment]
I think your best bet is now https://serialport.io/

**Comment by ShafSpecs** [comment]
> I think your best bet is now https://serialport.io/

That's what I was using but they don't have events so you can't create a hotplugging system. Except via smthg like intervals which is super inefficient especially when I'm not plugging/unplugging every 10 seconds. I was thinking of using this with it and cross checking the serial numbers but this doesn't seem to recognize UART devices

**Comment by thegecko** [comment]
Using both is one way we do it, but it relies on all your devices having a serial number:

- node-usb hotplug event > serialnumber
- use serialnumber in serialport to find device > com port
