### ISSUE TITLE
not able to use the printer any more after installing winusb driver with zadig

### ISSUE THREAD

**Issue by tsadak** [tessel/node-usb#187]
hello

I have a kiosk printer that i wanted to communicate via node-usb. but after installing the winUSB printer driver with Zadig and resetting the device just for a test i cannot access the printer any more, although i tried to remove and reinstall the device - it does not now even appear as printer but unknown device. how can i go back to use my printer again? and one more question. can i use the printer with its normal driver and access it via node-usb(just to get its status) at the same time?

**Comment by kevinmehall** [comment]
You should be able to uninstall the WinUSB driver from the device in Device Manager (note that it may appear as multiple entries if it has multiple interfaces), and then reinstall the printer vendor software. On Windows, devices can only be bound to one driver at a time.
