### ISSUE TITLE
InEndpoint.startPoll performance issue

### ISSUE THREAD

**Issue by michaelsogos** [tessel/node-usb#190]
Dear @kevinmehall.

I'm writing a driver for Epson Fiscal Printer with your amazing usb driver for nodejs (used with electron), and till now everything seems to work fine, i mean i can work with my usb device at low level.
But i discovered that the startPoll method is CPU consuming.

For a properly communication with EPSON fiscal printer, usually from Nodejs (aka server) i send a command to the printer, then the printer send back an ACK and in a separated buffer the answer, then once received the answer from printer the server must send again an ACK.

For this reason i'm using startPoll(3,1000) and attaching on event 'data'; but the event is raised very often even if the printer is not sending nothing (empty buffer). This is the reason why it is CPU consuming.

Do you have suggestion on how to improve my below code, or how to "listening" for incoming data after the server sent a command to the printer?

FOLLOWING A VERY DUMMY CODE EXAMPLE:
```javascript
            var usb = require('usb');
            usb.on('attach', function (device) {
                console.log("usb attached");
                console.log(device);

                alert('ready!');

                device.open();
                var i = device.interfaces[0];
                i.claim();

                var ackReceived = false;

                var inio = i.endpoints[1];
                inio.startPoll(3, 1000);
                inio.on('data', function (data) {
                    if (data.length > 0) {
                        if (data[0] == 6) {//ACK received
                            console.log('Received ACK');
                            ackReceived = true;
                        }
                        if (ackReceived && data[0] == 2) {
                            console.log('Received DATA');
                            console.log(data);
                            out.transfer(char(6), function (error, data) {
                                console.log("Sent ACK");
                                console.log(error); // null, <Buffer 00, 00, 00, 00, 00, 00, 00, 00
                                console.log(data);
                            });
                        }
                    }
                });

                var out = i.endpoints[0];
                var command = char(2) + '26E10740174' + char(3);
                out.transfer(command, function (error, data) {
                    console.log("Sent DATA");
                    console.log(command);
                    console.log(error); // null, <Buffer 00, 00, 00, 00, 00, 00, 00, 00
                    console.log(data);
                });

            });

```
The code work in this way:
1. Listen on attaching USB to PC (just as test, in real i should verify VID and PID)
2. When device is attached CLAIM the interfaces
3. Start polling on IN endpoint
4. Send command from OUT endpoint
5. Immediately the printer send back an ACK (ASCII 6) and after that send back again an answer (everything occure in 2ms)
6. By EPSON documentation i have to send to the printer an ACK from server like to say "OK I RECEIVED EVERYTHING", but only after i received the printer answer.

An idea: Is advisable to start and stop polling, respectively before and after sent all commands needed? It should not occure very often because a user print a long list of command but only on USER ACTION from a front end (like pushing a button "PRINT RECEIPT").

What really means nTransfers=3, transferSize=maxPacketSize parameter on startPoll methods? It is not really clear to me.

Thanks for your time and any suggestion you can give me.

**Comment by kevinmehall** [comment]
You're receiving empty packets because the device is sending you empty packets in response to a transfer request. Ideally, the device would wait to respond until it had something useful to say.

`startPoll` simply keeps `nTransfers` of `transferSize` bytes each constantly active -- as soon as one completes, it sends you an event with the data, and restarts the transfer. This ensures there is always a transfer ready for the USB controller to process, keeping the bus utilization high to maximize bandwidth. However, in your case, it's just maximizing the number of empty packets you have to handle.

Assuming you're only looking for low-bandwidth status data, a workaround could be to only request transfers periodically. Use something like

```
function performRead() {
    inio.transfer(1024, function(error, data) {
        if (data.length > 0) {
            //...
        }
        setTimeout(performRead, 50);
    });
}
```

Adjust the timeout to balance CPU usage vs latency. If you are only expecting to receive data at certain times, you could make this only poll when necessary.
