### ISSUE TITLE
v1.3.0 not published in NPM

### ISSUE THREAD

**Issue by IvanSanchez** [tessel/node-usb#193]
I can see 1.3.0 tagged and released in github at https://github.com/tessel/node-usb/releases/tag/1.3.0 , but https://www.npmjs.com/package/usb displays 1.2.0 as the latest available.

**Comment by ravikp7** [comment]
Using git dependency is not reliable with npm 5 for now. It'd be better to have it published in npmjs.
npm/npm#16907
npm/npm#16898

**Comment by mhagmajer** [comment]
@tcr any news here, please?

**Comment by ColacX** [comment]
bump. I think version 1.3.0 might fix my problem.

**Comment by kevinmehall** [comment]
Published 1.4.0
