### ISSUE TITLE
Synchronous transfers and responses

### ISSUE THREAD

**Issue by hetsch** [tessel/node-usb#198]
This is more of a howto question than a bug report. It is not entirely clear for me if this library also supports synchronous transfera, where the thread blocks until the requested data os reponded by the device. `Libusb` seems to support sync and async IO (http://libusb.sourceforge.net/api-1.0/io.html) but I cannot find any examples how to achieve synchronous IO operations with node-usb. Right now I use `startPoll` on the IN-Endpoint that works fine, but I would need a strategy to immediately process the results (e.g. in a loop);

USB device programming is new to me, therefore, any suggestions or code examples would help me tremendously.

**Comment by kevinmehall** [comment]
This library only exposes the asynchronous API since blocking is considered a bad practice in Node.
