### ISSUE TITLE
Electron crashes when disabling Wireless Network

### ISSUE THREAD

**Issue by mm739521** [tessel/node-usb#199]
I'm running the usb package in my electron app on my Windows 7 machine.

While running the application, if I go into my Network Connections and disable my Wireless Network Connection, the application process completely stops and exits with code 3221225477.

When rerunning the application with the wireless network still disabled, it runs fine and the usb package works.  It only breaks when it's disabled midrun.

Is there any exception catching or known fixes to this issue?

**Comment by jrobeson** [comment]
@kevinmehall : this is a known issue with electron. it can be closed.
