### ISSUE TITLE
Undefined variable module_name in binding.gyp while trying to load binding.gyp

### ISSUE THREAD

**Issue by kingio** [tessel/node-usb#203]
**node-gyp**: 3.6.2
**node**: 6.11.1
**node-usb**: 1.1.0

Executed command: `node-gyp -C node_modules/usb/ clean configure --arch=ia32 rebuild`
Error:
```
Undefined variable module_name in binding.gyp while trying to load binding.gyp
```

What i'm doing wrong?

**Comment by kevinmehall** [comment]
You have to build with `npm install --build-from-source` or `./node_modules/.bin/node-pre-gyp -v rebuild`, not `node-gyp` directly.
