### ISSUE TITLE
v1.2.0-node-v48-linux-arm.tar.gz missing!

### ISSUE THREAD

**Issue by patafix18** [tessel/node-usb#205]
I can't download the "usb_bindin gs-v1.2.0-node-v48-linux-arm.tar.gz" file cause it's not available in the Releases Folder. Can you please reupload it?

**Comment by kevinmehall** [comment]
You have to build from source. There are no Linux binaries distributed with node-pre-gyp.

https://github.com/tessel/node-usb#installation
