### ISSUE TITLE
Cant able to install in windows

### ISSUE THREAD

**Issue by sugir93** [tessel/node-usb#206]
I cant able to install this module in windows.
Bellow are the errors while running npm install usb

node-pre-gyp http 404 https://github.com/tessel/node-usb/releases/download/1.2.0
/usb_bindings-v1.2.0-node-v57-win32-x64.tar.gz

gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallb
ack-to-build" "--module=D:\\workspace_nodejs\\RPI3\\_gateway\\SensorDrivers\\RA\
\USB\\node_modules\\usb\\src\\binding\\usb_bindings.node" "--module_name=usb_bin
dings" "--module_path=D:\\workspace_nodejs\\RPI3\\_gateway\\SensorDrivers\\RA\\U
SB\\node_modules\\usb\\src\\binding"
gyp ERR! cwd D:\workspace_nodejs\RPI3\_gateway\SensorDrivers\RA\USB\node_modules
\usb
gyp ERR! node -v v8.9.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd build --fallback-
to-build --module=D:\workspace_nodejs\RPI3\_gateway\SensorDrivers\RA\USB\node_mo
dules\usb\src\binding\usb_bindings.node --module_name=usb_bindings --module_path
=D:\workspace_nodejs\RPI3\_gateway\SensorDrivers\RA\USB\node_modules\usb\src\bin
ding' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (D:\workspace_nodejs\RPI
3\_gateway\SensorDrivers\RA\USB\node_modules\usb\node_modules\node-pre-gyp\lib\u
til\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi
ld_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "D:\\workspace_n
odejs\\RPI3\\_gateway\\SensorDrivers\\RA\\USB\\node_modules\\usb\\node_modules\\
node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd D:\workspace_nodejs\RPI3\_gateway\SensorDrivers\RA\USB\nod
e_modules\usb
node-pre-gyp ERR! node -v v8.9.1
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd build --fallback-to-build --module=D:\workspace_
nodejs\RPI3\_gateway\SensorDrivers\RA\USB\node_modules\usb\src\binding\usb_bindi
ngs.node --module_name=usb_bindings --module_path=D:\workspace_nodejs\RPI3\_gate
way\SensorDrivers\RA\USB\node_modules\usb\src\binding' (1)
npm WARN Error: EPERM: operation not permitted, scandir 'D:\workspace_nodejs\RPI
3\_gateway\SensorDrivers\RA\USB\node_modules\usb\node_modules\node-pre-gyp\node_
modules\request\node_modules\hawk\node_modules'
npm WARN  { Error: EPERM: operation not permitted, scandir 'D:\workspace_nodejs\
RPI3\_gateway\SensorDrivers\RA\USB\node_modules\usb\node_modules\node-pre-gyp\no
de_modules\request\node_modules\hawk\node_modules'
npm WARN   stack: 'Error: EPERM: operation not permitted, scandir \'D:\\workspac
e_nodejs\\RPI3\\_gateway\\SensorDrivers\\RA\\USB\\node_modules\\usb\\node_module
s\\node-pre-gyp\\node_modules\\request\\node_modules\\hawk\\node_modules\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'scandir',
npm WARN   path: 'D:\\workspace_nodejs\\RPI3\\_gateway\\SensorDrivers\\RA\\USB\\
node_modules\\usb\\node_modules\\node-pre-gyp\\node_modules\\request\\node_modul
es\\hawk\\node_modules' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.2.0 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sugirtharaj.s\AppData\Roaming\npm-cache\_logs\2017-11-23T1
2_44_18_555Z-debug.log

**Comment by kevinmehall** [comment]
Looks like a npm issue: https://github.com/npm/npm/issues/17747
