### ISSUE TITLE
frequency

### ISSUE THREAD

**Issue by zhaiyuzhai** [tessel/node-usb#219]
What is the maximum transmission rate that is supported?it seems like that 800hz
can cause loss of data。I hope someone can help me

**Comment by kevinmehall** [comment]
You can expect about 1MB/s throughput on USB full speed, 20-40MB/s on USB high speed, or higher for super speed for a well-implemented device with optimized transfer scheduling. The device controls which version of the USB protocol it uses, not this user-space library.

USB provides reliable delivery of data with retries. If you're losing data, it's a problem with the firmware or how you're using the device.
