### ISSUE TITLE
usb_bindings-v1.3.1-node-v51-linux-arm.tar.gz is missing

### ISSUE THREAD

**Issue by timoberlin** [tessel/node-usb#221]
The plugin "homebridge-awox" tries to get a package during the installation process. Unfortunately the package seems to be removed and I was wondering whether it can be deployed again?
```
node-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-node-v51-linux-arm.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for usb@1.3.1 and node@7.9.0 (node-v51 ABI, glibc) (falling back to source compile with node-gyp)
```

**Comment by kevinmehall** [comment]
There are no binary builds for Linux / ARM. It should build from source if you have the [dependencies](https://github.com/tessel/node-usb#installation).
