### ISSUE TITLE
Getting 404 while downloading ARM library

### ISSUE THREAD

**Issue by AmitChotaliya** [tessel/node-usb#224]
Hello,

I am getting 404 while downloading the ARM specific tar for raspberry pi. Has it been removed/moved?

node-pre-gyp ERR! Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.3.1/usb_bindings-v1.3.1-node-v47-linux-arm.tar.gz

**Comment by kevinmehall** [comment]
There are no binary releases for Linux or ARM. You have to build from source.
