### ISSUE TITLE
v1.4.x is not actually published to npm

### ISSUE THREAD

**Issue by rwaldron** [tessel/node-usb#233]
The latest version is 1.3.1 https://www.npmjs.com/package/usb

**Comment by kevinmehall** [comment]
The main change in 1.4.0 was broken, so I reverted it, released the other fixes as 1.3.1 and set `latest` back to it. 1.4.0 is still on NPM but I don't recommend using it.

**Comment by rwaldron** [comment]
Got it. I had closed this myself after I realized that you'd reverted the portion that released as 1.4.0.
