### ISSUE TITLE
Connect to a scanner

### ISSUE THREAD

**Issue by abdallahkadour** [tessel/node-usb#237]
I have a scanner `CannoScanLiDE 210`, and I would like to scan documents from a node script. My code is as follow:
```js
var usb = require('usb')
// usb.on('attach', function (device) {
var device = usb.findByIds(1193, 6410)
console.log(device)
device.open()
var iFace = device.interfaces[0]
iFace.claim()
var inEndpoint = iFace.endpoints[0]
inEndpoint.startPoll(3, 64)
inEndpoint.on('data', function (data) {
  console.log('data' + data)
})
inEndpoint.on('error', function (err) {
  console.log('Polling error  ' + err)
})
inEndpoint.on('end', function () {
  console.log('Polling end ')
})
```
Though, I don't get any data from the device.   Should I send a request to trigger the scan process? And if yes how this should look like?

**Comment by kevinmehall** [comment]
It likely uses a fairly complex protocol over USB that you'd have to reverse-engineer. If there is an existing driver, you should probably use that instead of trying to reimplement it in JS with this library.
