### ISSUE TITLE
i cant' open device and occured error LIBUSB_ERROR_ACCESS 

### ISSUE THREAD

**Issue by cofham** [tessel/node-usb#247]
`usb.on('attach', function(device) {
	device.open();
});`

but can't open device and error LIBUSB_ERROR_ACCESS 

how can i solve this problem?

**Comment by grigdodon** [comment]
@cofham hi. did you manage to solve this issue? thanks!

**Comment by KatherineGuerrero** [comment]
This always happens to me when I run the app without sudo, if I use sudo it works. Do you know how to give the app those permissions?

**Comment by kevinmehall** [comment]
On Linux you can add udev rules to give a user or group access to certain USB devices:
http://ask.xmodulo.com/change-usb-device-permission-linux.html

**Comment by juliusvaart** [comment]
Adding the MODE="0660" permissions and adding GROUP="plugdev" to all USB-devices fixed it for us on Ubuntu 20.04.

Add:
`SUBSYSTEM=="usb", MODE="0660", GROUP="plugdev"`

To:
`/etc/udev/rules.d/99-usb-permissions.rules`

Reload udev rules
`sudo udevadm control --reload-rules`

Reboot or replug USB-devices.
