### ISSUE TITLE
LIBUSB_TRANSFER_ERROR when device is unplugged

### ISSUE THREAD

**Issue by dindonus** [tessel/node-usb#256]
Hi,

i would like to use the startPoll() feature, but if the device is unplugged when polling is enable, then the app will crash.

I have no change to stopPoll() on the detach event, because the unhandled error came before the event.

Here is the error details, is this fixable ?

`events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: LIBUSB_TRANSFER_ERROR
Emitted 'error' event at:
    at Transfer.transferDone ([PATH]/node_modules/usb/usb.js:330:9)`

Thanks 😄

**Comment by kevinmehall** [comment]
It's only an unhandled error because the app isn't handling it. Add a listener for the `error` event on the endpoint.
