### ISSUE TITLE
Disable libudev

### ISSUE THREAD

**Issue by thundron** [tessel/node-usb#271]
Should I need to, how can I disable libudev? I see there's a `use_udev` config in `bindings.gyp` and `libusb.gypi` so I made a fork here https://github.com/thundron/node-usb that sets that property to 0, but I'd like to know if you have another way to disable it without rebuilding the module and maybe more important, if there are any other files I should modify to avoid using libudev.

**Comment by jviotti** [comment]
@thundron I believe you can do `GYP_DEFINES="use_udev=0"`. There shouldn't be a reason to fork
