### ISSUE TITLE
Read data for particular file on device.

### ISSUE THREAD

**Issue by kk-r** [tessel/node-usb#273]
I want to read the data of particular file (test.txt) from the device. Please Suggest me if there's any other way we can try this. Thanks.

**Comment by kevinmehall** [comment]
Unless you're planning to implement a USB Mass Storage class driver and a filesystem, this isn't the library for you. This library lets you make low-level requests to the device to implement drivers for new devices. Your OS already has drivers for Mass Storage devices like flash drives, so you should use that via the `fs` API.
