### ISSUE TITLE
Remove `aws-sdk` dev dependency

### ISSUE THREAD

**Issue by HipsterBrown** [tessel/node-usb#290]
This dependency has been causing issues (#215) and does not appear to be used anymore since `node-usb` switched to using `node-pre-gyp-github` to host binaries on GitHub a few years ago. 

I think we can safely remove it now.

**Comment by milonite** [comment]
Agree with this #https://github.com/LedgerHQ/ledgerjs/issues/242

**Comment by HipsterBrown** [comment]
Ok this is open to anyone as a great first contribution. Otherwise, I'll add it to my Bug Fix Friday list. 😄

**Comment by rohan-malik** [comment]
Could you kindly assign this bug to me?

**Comment by rohan-malik** [comment]
I've added a pull request for this issue:

https://github.com/tessel/node-usb/pull/295/commits/fce72ce7664e9e6e5753fdbc684a012a6e710386

**Comment by jrobeson** [comment]
Fixed in https://github.com/tessel/node-usb/pull/300
