### ISSUE TITLE
LIBUSB_ERROR_ACCESS on OSX as admin user

### ISSUE THREAD

**Issue by GCheung55** [tessel/node-usb#30]
interface[0].claim() is throwing this error.

I installed pkg-config and libusbx via: `brew install libusbx pkgconfig`.

libusbx-1.0.17 and pkg-config-0.28 were installed.

**Comment by djMax** [comment]
What about if the device is inbound only? I don't quite get how to just wait for inbound bytes on (for example) a magnetic card reader...

**Comment by kevinmehall** [comment]
@djMax, you probably want to perform a transfer on an IN endpoint. A magnetic card reader may be a HID class device and be claimed by a kernel driver.

**Comment by djMax** [comment]
Yeah, it is a HID. node-hid doesn't work in 0.12 yet so I was hoping to use this module. But it seems like that's not possible? (I downgraded to 0.10 and node-hid works for my purposes there, but 0.12 would be better for node-webkit and the like)

**Comment by kevinmehall** [comment]
On Linux it is possible to call `detachKernelDriver` to take control of the device back from the kernel driver, and on Windows you can change the driver with Zadig, but AFAIK on OS X the only way to prevent the kernel driver from binding is to write your own kext to claim it first.

**Comment by 360disrupt** [comment]
What exactly does `claim()` do. When I remove it I don't get this error anymore but I get this error instead:
(LIBUSB_ERROR_NOT_FOUND)[https://github.com/nonolith/node-usb/issues/61] so I guess it is required to call that method. @tristil can you post some code how you read your usb device without claim. Thx

**Comment by tristil** [comment]
@360disrupt see https://github.com/tristil/usb-rocket-launcher-node/blob/master/launcher.js#L119 You might be getting an unrelated error related to finding the device btw

**Comment by 360disrupt** [comment]
> unrelated error related to finding the device btw

I get `LIBUSB_ERROR_NOT_FOUND` should I just catch and ignore that? My code:

```
usb = require('usb')
self = @

exports.pollCoinSelector = (appUser, callback)->
  idVendor = 4660
  idProduct = 17185
  coinSelector = usb.findByIds(idVendor, idProduct)
  coinSelector.open()
  return callback "Did not find coin selector!" if !coinSelector? #TODO ERROR HANDLING -> EMAIL, SCREEN MAINTAINANCE
  self.pollUsbDevice(coinSelector, callback)

exports.pollUsbDevice = (device, callback) ->
  return callback "No Interface" if !device.interfaces?[0]?
  iface = device.interfaces[0]
  # iface.claim()

  return callback "No Endpoint" if !iface.endpoints?[0]?
  inEndpoint = iface.endpoints[0]

  inEndpoint.startPoll 8, 64
```

**Comment by tristil** [comment]
@360disrupt I'm not sure, sorry. On that other issue they seem to be saying that it's a device specific problem. You might want to experiment with passing 0 or 1 to claim but that's just a guess.

**Comment by sofroniewn** [comment]
@360disrupt were you able to get the reading working? I'm running into the same errors - `Error: LIBUSB_ERROR_ACCESS` if I call `claim`, and `Error: LIBUSB_ERROR_NOT_FOUND` if I try and `startPoll` without calling claim.

The advice of trying `__claimInterface(0)`, as suggested here https://github.com/tessel/node-usb/issues/61, also didn't work for me.

Any advice would be much appreciated. Thanks

**Comment by sofroniewn** [comment]
The device I'm trying to connect to is an optical gaming mouse from logitech http://support.logitech.com/en_us/product/gaming-mouse-g300

**Comment by kevinmehall** [comment]
If you are on OSX, you cannot use this library with HID devices, including mice, keyboards, gamepads, etc. OSX has a kernel driver for HID devices, and does not support detaching kernel drivers.

**Comment by sofroniewn** [comment]
Ah ok - thanks very much for that information. I am trying to read the x,y deltas from multiple usb mice in node. Do you happen to know of any libraries that would allow me to do that on OSX? Thank you for your time.

**Comment by kevinmehall** [comment]
To be included in #182.

**Comment by arezd** [comment]
@sofroniewn 
Did you finally find a solution for mac. I am trying to do the exact same thing as you do with the mouse and the x,y thing :)
Thanks

**Comment by sofroniewn** [comment]
Nope afraid not, sorry

**Comment by mcuee** [comment]
Please refer to this discussion, libusb-1.0.26 adds the support to detach kernel driver with correct entitlement (which is diffcult to get from Apple) but at least you can run as root.
* https://github.com/libusb/libusb/issues/1014
