### ISSUE TITLE
Process finished with exit code -1073740771 (0xC000041D) when requiring "usb"

### ISSUE THREAD

**Issue by Mushroomizer** [tessel/node-usb#303]
When requiring the usb module.
Plugging in / removing a smart card reader causes the process to exit.

https://github.com/tessel/node-usb/issues/285 is a related issue.

**Comment by icebale** [comment]
I met same issues,the following is my solution
cd node_modules/usb;
node-gyp rebuild --target=4.0.0 --dist-url=https://atom.io/download/atom-shell

The --target flag for the last command specifies the version of electron you’re building for and must be set accordingly.

hope this can help you

**Comment by Mushroomizer** [comment]
Thanks @icebale, much appreciated
