### ISSUE TITLE
prebuild Add Electron 4.1 & 4.2

### ISSUE THREAD

**Issue by GuoJing1995** [tessel/node-usb#319]
I use sqlite3 and node-usb, but the sqlite3 prebuild Electron 4.1 & 4.2

**Comment by kevinmehall** [comment]
4.1 and 4.2 are not [listed](https://github.com/nodejs/node/blob/master/doc/abi_version_registry.json) as separate ABI versions from 4.0.4.

5, 6, and 7 added in 1.6.1.
