### ISSUE TITLE
Why is ISerialNumber only one

### ISSUE THREAD

**Issue by GanZhiXiong** [tessel/node-usb#328]
![image](https://user-images.githubusercontent.com/27394631/65577362-3a77b680-dfa6-11e9-946b-2ef3f26edf88.png)

**Comment by kevinmehall** [comment]
It's the index of the string descriptor containing the serial number. Pass it to `getStringDescriptor` to fetch the actual serial number string from the device.

**Comment by GanZhiXiong** [comment]
The following code I found from the other issue does open () before calling getStringDescriptor
Do you have to open the device to call getStringDescriptor？ 

```
device.open();
device.getStringDescriptor(deviceDescriptor.iManufacturer, function (err, manufacturer) {
  device.getStringDescriptor(deviceDescriptor.iProduct, function (err, product) {
    device.getStringDescriptor(deviceDescriptor.iSerialNumber, function (err, serialNumber) {
      console.log(manufacturer, product, serialNumber);
      device.close();
    });
  });
});
```

**Comment by kevinmehall** [comment]
Yes

**Comment by GanZhiXiong** [comment]
Because our device's idVenDor and idProduct are the same, I can't determine which device I'm connected to, unless I connect a device and then differentiate it based on the Serialnumber of the device, which becomes a bit cumbersome.
