### ISSUE TITLE
yarn install breaks in prebuild

### ISSUE THREAD

**Issue by Gayathri-Rajamanickam-MindTree** [tessel/node-usb#330]
Hi,

We are using electron v 5.0.2 and nodejs version 10, node-usb 1.6.0 

During yarn install, it fails in the following command

prebuild-install http request GET __https://github.com/tessel/node-usb/releases/download/v1.6.0/usb-v1.6.0-electron-v70-win32-x64.tar.gz 

While analyzing, we see that this link is no more valid --> https://github.com/tessel/node-usb/releases/download/v1.6.0/usb-v1.6.0-electron-v70-win32-x64.tar.gz

can anyone help us to fix this issue?

Regards,
Gayathri

**Comment by kevinmehall** [comment]
Electron 5, 6, and 7 prebuild added in 1.6.1.
