### ISSUE TITLE
No Endpoints in Interface

### ISSUE THREAD

**Issue by RedETV** [tessel/node-usb#341]
Hello, I'm trying to connect my Alesis Keyboard to my computer and see if I can grab the keys being pressed. However, while I can claim the first interface ( interfaces[ 0 ] ), there are no endpoints within that interface. However, the second interface ( interfaces[ 1 ] ) has both InEndpoint and OutEndpoint.  But if I try to claim said interface, it gives me the following error:

> Error: LIBUSB_ERROR_NOT_SUPPORTED                                                                                           at Interface.claim (D:\Piano Interface\node_modules\usb\usb.js:280:14)                                                  at Object.<anonymous> (D:\Piano Interface\index.js:7:30)                                                                at Module._compile (internal/modules/cjs/loader.js:778:30)                                                              at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)                                                at Module.load (internal/modules/cjs/loader.js:653:32)                                                                  at tryModuleLoad (internal/modules/cjs/loader.js:593:12)                                                                at Function.Module._load (internal/modules/cjs/loader.js:585:3)                                                         at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)                                                      at startup (internal/bootstrap/node.js:283:19)                                                                          at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3) 

I'm not sure how to diagnose this, and was wondering if maybe it has to do with how Zadig recognizes and installs the driver? Within Zadig, the device appears as "Alesis Recital (Interface 0)".

Thanks in advance!

**Comment by kevinmehall** [comment]
LIBUSB_ERROR_NOT_SUPPORTED usually means that the device does not have the WinUSB driver attached properly (e.g. with Zadig). For composite devices it's a little tricky. There will be multiple entries for the device in Zadig, and you'll need to install it for all the interfaces, or the composite parent representing the device as a whole.

If the default driver is a generic class like HID or MIDI, there may be a more specific library that can access the device without needing to replace the driver.
