### ISSUE TITLE
How to do multiple control transfers elegantly with callback?

### ISSUE THREAD

**Issue by Newbrict** [tessel/node-usb#346]
Hi, this isn't an "issue" per se, I just wanted to understand what the proper way to port over c usage of the libusb library to js with callback is.

My c code basically does 20 `controlTransfer`s in a loop while incrementing the `wValue` and `wIndex` parameters. I'm wondering how to elegantly reproduce this given that node-usb uses callbacks. What I thought of and really want to avoid is something like this:
```js
handle.controlTransfer(bmRequestType, bRequest, wValue, wIndex, data, (err) => {
    if (err) {
        console.log("error occurred");
    } else {
        handle.controlTransfer(bmRequestType, bRequest, wValue+x, wIndex+y, data, (err) => {
            if (err) {
                console.log("error occurred");
            } else {
                // on and on and on....
            }
        });
    }
});
```
Please advise :^) thank you!

**Comment by kevinmehall** [comment]
This is more of a general JavaScript question. There are many resources on async control flow patterns in JS progressing from callbacks to promises to async/await. https://zellwk.com/blog/nested-callbacks/ looks like a good place to start.

`node-usb` has an API that pre-dates promises and async/await, but it's easy to adapt to promises using [util.promisify](https://nodejs.org/api/util.html#util_util_promisify_original) and that's the best way to deal with this in modern JS.

**Comment by Newbrict** [comment]
Thank you!
