### ISSUE TITLE
How to read from device, can someone explain

### ISSUE THREAD

**Issue by markosole** [tessel/node-usb#356]
I am looking for a way to read from device (barcode scanner). I just do not know how to do something like `mydevice.on('data', .....)` as this would not work. I can open device, It does not complain after using  mydevice.open() but I do not know what to do after that. I've tried `mydevice.startPoll(8, 64);`
but it says "on" is not a function. I don't get it.

Thanks in advance.

**Comment by kevinmehall** [comment]
See my response to the same question on https://github.com/tessel/node-usb/issues/258
