### ISSUE TITLE
no suitable image found

### ISSUE THREAD

**Issue by saifeiLee** [tessel/node-usb#367]
![image](https://user-images.githubusercontent.com/28710808/84756681-b4007a80-aff5-11ea-9911-8ea627111de8.png)

Could anyone please explain why it happens?

**Comment by kevinmehall** [comment]
Same as https://github.com/tessel/node-usb/issues/360 except now you've got a Linux binary on macOS. Are you sharing an install directory between operating systems?

**Comment by saifeiLee** [comment]
> Same as #360 except now you've got a Linux binary on macOS. Are you sharing an install directory between operating systems?

Thanks for replying.
I only run my app on osx. No other system.But I package my app for linux by electron-builder. Is the packaging for linux causing the issue？

**Comment by kevinmehall** [comment]
I've never used electron-builder, no idea.

**Comment by saifeiLee** [comment]
> I've never used electron-builder, no idea.

Thank you all the same. May you have a lovely day~
