### ISSUE TITLE
Not Found 404 releases/download/v1.6.3/usb-v1.6.3-node-v83-linux-arm.tar.gz

### ISSUE THREAD

**Issue by ferhattelci** [tessel/node-usb#369]
Hi all, 

i cannot download the package .. while downlading i'm getting these error lines ..

 npm install --unsafe-perm usb

> usb@1.6.3 install /home/pi/Printer/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.5
prebuild-install info looking for cached prebuild @ /home/pi/.npm/_prebuilds/cd9f6c-usb-v1.6.3-node-v83-linux-arm.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-linux-arm.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v83-linux-arm.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=14.2.0 runtime=node arch=arm libc= platform=linux)
gyp ERR! UNCAUGHT EXCEPTION
gyp ERR! stack TypeError: tar.extract is not a function
gyp ERR! stack     at Request.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/install.js:199:22)
gyp ERR! stack     at Request.emit (events.js:327:22)
gyp ERR! stack     at Request.onRequestResponse (/usr/local/lib/node_modules/npm/node_modules/request/request.js:1066:10)
gyp ERR! stack     at ClientRequest.emit (events.js:315:20)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:634:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:503:22)
gyp ERR! stack     at TLSSocket.emit (events.js:315:20)
gyp ERR! stack     at addChunk (_stream_readable.js:302:12)
gyp ERR! stack     at readableAddChunk (_stream_readable.js:278:9)
gyp ERR! System Linux 4.19.118+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Printer/node_modules/usb
gyp ERR! node -v v14.2.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! This is a bug in `node-gyp`.
gyp ERR! Try to update node-gyp and file an Issue if it does not help:
gyp ERR!     <https://github.com/nodejs/node-gyp/issues>
npm WARN NN.JugOrder.Printer@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! usb@1.6.3 install: `prebuild-install --verbose || node-gyp rebuild`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the usb@1.6.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-07-04T21_07_30_231Z-debug.log

Is there are any workarounds?

Thanks in advance!

**Comment by kevinmehall** [comment]
The 404 part is expected; we don't offer prebuilds for ARM. It should then build from source, though.

The `TypeError: tar.extract is not a function` appears to be a symptom of a broken installation of Node:

https://github.com/nodejs/node-gyp/issues/2067
https://github.com/nodejs/node-gyp/issues/1871
