### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by k4113h** [tessel/node-usb#382]
Is it valid for this project to use MIT license as it depends on libusb that uses LGPL-2.1?

**Comment by kevinmehall** [comment]
Yes. The MIT license covers the code in this repository only. If you distribute a combined work containing both node-usb and libusb you must comply with both licenses.

**Comment by k4113h** [comment]
> Yes. The MIT license covers the code in this repository only. If you distribute a combined work containing both node-usb and libusb you must comply with both licenses.

Thank you, this clarifies it.
