### ISSUE TITLE
iOS Serial Length 

### ISSUE THREAD

**Issue by qin-young** [tessel/node-usb#384]
Obtaining the serial number of the Apple device always returns a string of length 40, but some Apple devices have a serial number of only 24 ，For me ，it work by format the serial 
```
const format = (data) => {
  var regx = /^[A-Za-z0-9]*$/
  var serial = ''
  for(let i = 0; i < data.length; i++) {
    if(regx.test(data.charAt(i))){
      serial += data.charAt(i)
    }
  }
  if(serial.length === 24){
    return serial.substr(0,8) + '-' +serial.substr(-16)
  }
  return serial
}
```

**Comment by kevinmehall** [comment]
This seems very device-specific and isn't related to node-usb. Hope this code helps anyone with the same problem, though!
