### ISSUE TITLE
Please add support for electron v10 on Windows

### ISSUE THREAD

**Issue by quinton-ashley** [tessel/node-usb#389]
Building from source doesn't work and neither does using prebuilt binaries.
```
    prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-electron-v82-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=10.1.3 runtime=electron arch=x64 libc= platform=win32)
```

**Comment by thegecko** [comment]
This was added in #404, feel free to close.

cc @kevinmehall

**Comment by kevinmehall** [comment]
Thanks to @thegecko's help, v1.6.4 has been released with prebuilds for Node 14 and Electron 9, 10, 11, and 12-beta1.
