### ISSUE TITLE
bluetooth doesn't work after electron app packaged

### ISSUE THREAD

**Issue by lkurylo** [tessel/node-usb#395]
I'm developing an Electron app to connect to bluetooth BLE device using @abandonware/noble on Windows 10. Everything works in development but not when I package the app using electron-builder.
I believe this is problem with this missing package for usb. 
How to fix it? Can I build this myself and how can I do this?

![electron-builder](https://user-images.githubusercontent.com/744244/99890612-81704300-2c61-11eb-8f86-b917a2812671.PNG)

**Comment by kevinmehall** [comment]
v1.6.4 has been released with prebuilds for Node 14 and Electron 9, 10, 11, and 12-beta1.
