### ISSUE TITLE
It only reads a random byte

### ISSUE THREAD

**Issue by CenekSanzak** [tessel/node-usb#402]
I have a esp32 device connected by usb. It writes a string with length 10-20 every second. But in the data event, there is a buffer with 1 byte. In first events it has more bytes and they are meaningless too. 

if(interface.isKernelDriverActive())interface.detachKernelDriver()
            interface.claim()
            const inend = interface.endpoints[0]
            outend = interface.endpoints[1]
            inend.startPoll()
            inend.on('data', data => {
    const datastr = data.toString("binary")
    console.log(datastr, datastr.length, data.length)
    console.log(datastr.split('').map(c=>c.charCodeAt()))
    })

output is:
ï 1 1
[ 239 ]
÷Öüúýýý÷þÿýý÷¿þïýýÿÿýýýÿgÕùúýõõõõÿýëÿõýÿ÷Ôþú÷õÿþõÿýýÒõýýõwþúû÷ÿÿ 64 64
[
  247, 214, 252, 250, 253, 253, 253, 247, 254,
  255, 253, 253, 247, 191, 254, 239, 253, 253,
  255, 255, 253, 253, 253, 255, 103, 213, 249,
  250, 253, 245, 245, 245, 245, 255, 253, 235,
  255, 245, 253, 255, 247, 212, 254, 250, 247,
  245, 255, 254, 245, 255, 253, 253, 210, 245,
  253, 253, 245, 119, 254, 250, 251, 247, 255,
  255
]
þûýýîýþý·¿ûõû÷ÿÿõïýÿýýþý¿¿×ÿ÷ëïþõþÿÿÿõõýÿ¿ßùûÛ÷õÿõþÿÿgýþõ÷÷×ÿûõý 64 64
[
  254, 251, 253, 253, 238, 253, 254, 253, 183,
  191, 251, 245, 251, 247, 255, 255, 245, 239,
  253, 255, 253, 253, 254, 253, 191, 191, 215,
  255, 247, 235, 239, 254, 245, 254, 255, 255,
  255, 245, 245, 253, 255, 191, 223, 249, 251,
  219, 247, 245, 255, 245, 254, 255, 255, 103,
  253, 254, 245, 247, 247, 215, 255, 251, 245,
  253
]
õõÕéýÛÛõþïõýüÖ÷ýÿîþþýÛýëþëõ÷ýÿúýýýþýíÿß 39 39
[
  245, 245, 213, 233, 253, 219, 219,
  245, 254, 239, 245, 253, 252, 214,
  247, 253, 255, 238, 254, 254, 253,
  219, 253, 235, 254, 235, 245, 247,
  253, 255, 250, 253, 253, 253, 254,
  253, 237, 255, 223
]
ß 1 1
[ 223 ]
ý 1 1
[ 253 ]

**Comment by kevinmehall** [comment]
Are you reading from the right interface and endpoint? Check the interface and endpoint descriptors (on Linux: `lsusb -v -d VID:PID`). And what protocol does the device implement? Since you're talking about sending lines and not packets it sounds like an emulated serial port -- if that's CDC ACM serial you should be using `node-serialport` rather than `node-usb`.
