### ISSUE TITLE
Linux build failed

### ISSUE THREAD

**Issue by pavinthan** [tessel/node-usb#406]
prebuild info begin Prebuild version 10.0.1
prebuild info build Preparing to prebuild usb@1.6.4 for electron 11.0.0 on linux-x64 using node-gyp
prebuild verb starting build process node-gyp 
prebuild verb execute node-gyp with `node index.js rebuild --target=11.0.0 --target_arch=x64 --runtime=electron --dist-url=https://atom.io/download/electron` 

![image](https://user-images.githubusercontent.com/13897936/105715171-46c9a600-5f43-11eb-9fb1-5f7d25ccc892.png)

**Comment by kevinmehall** [comment]
Screenshot is of Travis-CI, which has been replaced by GitHub Actions. If you're having trouble building locally, this does not include any error messages that would be useful for debugging it. Look at the recent commits for a few compiler settings changes that may help.
