### ISSUE TITLE
Why my getStringDescriptor return error uninitialized  even after device.open?

### ISSUE THREAD

**Issue by jimmyrogue** [tessel/node-usb#415]
```
const msDevice = USB.findByIds(xxxx,xxxxx);
msDevice.open();
msDevice.getStringDescriptor(
    msDevice.deviceDescriptor.iManufacturer,
    (error, data) => {
      // console.log('getStringDescriptor error', error);
      console.log('stringDescriptor', String(data), String(error));
    }
  );
```

console.log = stringDescriptor undefined uninitialized

help me plz

**Comment by thegecko** [comment]
Using `String(data)` may not cast the buffer in the way you want.

Perhaps refer to this convenience method as an example for getting the string descriptor:

https://github.com/tessel/node-usb/blob/v2.0.0/tsc/index.ts#L27
