### ISSUE TITLE
process exit results in a SIGABRT (exit code 134)

### ISSUE THREAD

**Issue by ms270169** [tessel/node-usb#430]
When using module `usb` in my electron application, a program exit (`app.quit()`, `app.exit(0)` or `process.exit(0)`) always results in an `Aborted` with exit code 134.

Used versions:
* Debian 10
* Electron v13.1.2 (Node 14.16.0)
* usb v1.7.1

The program only uses `usb.on('attach', ...)` and `usb.on('detach', ...)`, and `removeListener(...)` before exit.

According to [https://nodejs.org/api/process.html](https://nodejs.org/api/process.html) : 
> \>128 Signal Exits: If Node.js receives a fatal signal such as SIGKILL or SIGHUP, then its exit code will be 128 plus the value of the signal code. This is a standard POSIX practice, since exit codes are defined to be 7-bit integers, and signal exits set the high-order bit, and then contain the value of the signal code. For example, signal SIGABRT has value 6, so the expected exit code will be 128 + 6, or 134.

**Comment by thegecko** [comment]
I believe this has been fixed with https://github.com/tessel/node-usb/pull/440

Please reopen if this is not the case
