### ISSUE TITLE
"Failed to initialize libusb" on a clean install

### ISSUE THREAD

**Issue by IceCrafter** [tessel/node-usb#446]
Hello! I just freshly installed this module. I ran the prerequisite `sudo apt-get install build-essential libudev-dev` . I am running Ubuntu 20.04 LTS on Windows using WSL 2 with Node 16.8. I just tried starting the program, and it keeps throwing the error mentioned in the title. It doesn't matter what i try, it always tells me that the initilalization failed. Here's a code snippet of what i am trying:

![image](https://user-images.githubusercontent.com/43503752/132106042-cd5511fa-f24e-49c2-9839-c32ce58a87d9.png)

It errors on any function, even just the setDebugLevel. I tried googling for like an hour, where i found `sudo apt-get install libusb-dev usbutils`, which also didn't fix it. I tried everything from restarting to `apt update`, different node versions, etc. I don't know if its an issue with the module or with my setup, terribly sorry if its the second thing, but I can't find any more stuff I haven't tried yet. I am running this on my normal home PC, which definitely has USB ports. Help is really appreciated, thanks!

**Comment by kevinmehall** [comment]
I don't think WSL supports USB. You'd need to run the Windows version of Node and node-usb, use a VM like VirtualBox that supports USB passthrough, or run Linux natively.
