### ISSUE TITLE
apple rejects app for app store for non-public or deprecated APIs  in  node-usb

### ISSUE THREAD

**Issue by MvLindenberg** [tessel/node-usb#582]
I'm trying to get my electron app that uses node-usb for apple approved for the app store but apple won't approve it because:

Your app uses or references the following non-public or deprecated APIs:

• Contents/Resources/app.asar.unpacked/node_modules/usb/build/node_gyp_bins/python3/_Py_Initialize

The use of non-public or deprecated APIs is not permitted on the App Store, as they can lead to a poor user experience should these APIs change and are otherwise not supported on Apple platforms.

**Comment by thegecko** [comment]
Looks like you are including tools used to build node-usb. The build folder suggests you are building this locally and not using the prebuilds
